# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 779f65f091c0a7635c59776410318a16d503b0a3bc535098399f14adf80463f068164019d8e748f54af2bfbbcdd94d70e1493eaf4f977e4eefa2f57a16f86f58

test:
  secret_key_base: 3cfb5d8affd79545963090e52acca986acf0fcf550d008298507607432917356423d4addf034caf0fc175a3bed160c16ec693ff1a6f84d9a373d1cf3620a9cbd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
